구글 소셜 로그인 완료
gdsc-ssu/emotimer pull request #2
Opened 2022-06-02 12:24 UTC by yeonnex

구글 로그인 완료하였습니다.
로그인 성공시 이후 요청의 인가처리를 위해 access token 과 refresh token 을 요청 헤더에 담아 응답합니다.

프론트에서 서버로 요청시 해주셔야 할 일은, 
**요청 헤더**에 발급받은 **액세스 토큰**을 **"Authorization" 을 key** 로 갖고, **"Bearer " 를 prefix** 로 붙여 **서버로 전송**해주시면 **인증처리**를 시작할 수 있습니다.

현재 액세스 토큰은 테스트를 위해 1분으로 해두었으며, 액세스 토큰 만료시 클라이언트에게 익셉션 메시지를 응답하고 있습니다. 원래대로라면 액세스 토큰이 만료되어 권한이 없어지므로 다시 로그인페이지로 돌아갔었지만, "/refresh" api 를 호출하여 액세스 토큰을 재발급 받게 하기 위해 현재는 클라이언트에게 "/refresh api 를 호출해주세요" 라는 에러 익셉션 메시지를 화면에 그대로 주고 있습니다.

현재 모든 api 응답에 체계화된 구조가 없는데, 이후 회의를 통해 결정하도록 하겠습니다.

2022-06-18 07:40 UTC, enif-lee requested changes
리뷰 남겨보았습니다.

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/UserService.java
> +public class UserService {
오잉 요건 비어있는 걸까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserController.java
> +//    @PostMapping("/test") // POST 요청은 csrf 설정을 따로 해주지 않는다면 다른 서버에서 POST 등 리소스의 상태를 변경하는 동작 아예 수행 불가.
주석은 최대한 삭제해주세요~!

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/AuthController.java
> +        UserRefreshToken userRefreshToken = userRefreshTokenRepository.findByEmailAndRefreshToken(email, refreshToken);
아하 구두로 논의했듯 pk 기반으로 바꿔보시면 좋을 것 같아요.

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/AuthController.java
> +
요런 공백은 가급적이면 없으면 좋을 것 같아요~ java 린트 도구 도입해보면 좋을 듯..?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        params.add("client_secret", "aTnSYwnw2qCJ0zZ9Br74HUUoWS0kMVwy");
헉 이런건 가급적 environment value로 분리해주세요.

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        // HttpHeader 와 HttpBody 를 하나의 오브젝트에 담기
ㅋㅋ 중복!

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        System.out.println("==response==" + response1);
삭제 삭제

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        ResponseEntity<String> response2 = rt2.exchange(
요로한 api 송수신에 대해서 KakaoAuthClient 같은 클라이언트로 별도로 추상화해서 정의하는게 어떨까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserController.java
> +    @GetMapping("/") // 메인 페이지. 소셜 로그인할 수 있는 링크들 있음.
어떤 용도일까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserDetailController.java
> +public class UserDetailController {
`UserDetailController`보다는 `/users` 하위의 모든 api는 가급적 `UserController`에서 작성하는게 어떨까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserDetailController.java
> +    @GetMapping("/email")
구현된 내용이 없는 것 같긴한데. `GetMapping("/me")` 정도면 좋을 것 같아요.

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/auth/AuthReqModel.java
> +public class AuthReqModel {
어디서 쓰이는 메세지일까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/user/User.java
> +@Table(name = "USER")
db naming convention은 uppercase로 결정된 것일까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/OAuth2Service.java
> +                throw new OAuthProviderMissMatchException(
오잉 요건 어떤 용도로 정으된 예외일까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/OAuth2Service.java
> +@RequiredArgsConstructor
요건 왜 필요한 걸까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/common/ApiResponse.java
> +public class ApiResponse<T> {
특별한 이유가 없다면 기본적으로 제공되는 HttpResponse 를 사용하는게 좋을 것 같아요

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/config/properties/AppProperties.java
> +public class AppProperties {
application.properties에서 사용되는 걸까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/config/security/SecurityConfig.java
> +                .antMatchers("/api/**/user/**").hasAnyAuthority(RoleType.USER.getCode()) // "/api/**" USER 권한이 있어야 접근가능.
`/api/**`
`/admin/api**` 요로케하면 좋지 않을까요? 

timer api의 경우에는 `/api/timer`요론식으로 진행될 것 같아서 아마 위 matcher로는 조금 아쉬울 것 같아요

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/entity/RoleType.java
> +    GUEST("ROLE_GUEST", "게스트 권한");
게스트 권한도 있으면 좋을 것 같긴 한데 어떻게 사용하면 좋을까요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/filter/TokenAuthenticationFilter.java
> +        log.info("이후 필터를 타는가?");
요론 로그는 없어도 댈듯여 ㅋ ㅋ ㅋ

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        if (response.isCommitted()){
요건 어떤 의민가용? (몰라서...

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        response.setHeader("access_token" , accessToken.getToken());
헤더로 반환하기 보단

```
{
  "access_token": "",
  "refresh_token": "",
  "access_expiry": DateTime
  "refresh_expirty": DateTime
}
```
형태로 json 바디로 내려주면 좋을 것 같아요. 해더에도 물론 내려줄 수는 있지만, 보통 헤더는 바디나 요청에 대한 설명을 담는 용도로 사용되는데요. api가 발급이니까 -> 발급의 결과는 바디에 담는 형태가 좋을 것 같아요.

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +                    if(authorizedURI.getHost().equalsIgnoreCase(clientRedirectUri.getHost())
아래 로직은 그냥
```
return authorizedURI.getHost().equalsIgnoreCase(clientRedirectUri.getHost()) && authorizedURI.getPort() == clientRedirectUri.getPort()
```
로 줄일 수 있어보입니다~

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/info/OAuth2UserInfoFactory.java
> +//            case KAKAO: return new KakaoOAuth2UserInfo(attributes);
카카오는 아직 안되어있는거죵? 구현이 있는 것 같아서요~

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/info/impl/GoogleOAuth2UserInfo.java
> +public class GoogleOAuth2UserInfo extends OAuth2UserInfo {
Info 보단 다른 이름이 적절해보이긴 하는데 흠 조금 고민이 되네요 ㅠ

1. Properties
2. State
3. Details 

이런 후보가 있을 것 같아요.

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/CustomOAuth2UserService.java
> +    private OAuth2User process(OAuth2UserRequest userRequest,OAuth2User user){
`updateOrCreate` 정도로 명명해도 괜찮을 것 같아요

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/CustomOAuth2UserService.java
> +    private OAuth2User process(OAuth2UserRequest userRequest,OAuth2User user){
그럼 주석도 지워도 될듯?!

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/CustomOAuth2UserService.java
> +        if(userInfo.getUserName() != null && ! ( userInfo.getUserName().equals(userInfo.getImageUrl()) )){
user name과 image url을 비교하는 것 같아요

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +        // access token
주석 삭제 삭제

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +        AuthToken newAccessToken = tokenProvider.createAuthToken(
엑세스 토큰은 새로 발급하는 것 같은데 refresh 토큰은 어디에 발급하나요?

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +    public void refreshToken(HttpServletRequest request, HttpServletResponse response){
HttpServiceRequest/Response을 받아서 상태를 가져오거나 수정하는 것 보다는 parameter와 return으로 필요한 값들을 노출시키는 것이 더 좋은 것 같아요

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +    public void refreshToken(HttpServletRequest request, HttpServletResponse response){
그리고 그것을 사용해서 response 를 만드는 것은 온전히 controller의 책임이구여

2022-06-18 07:40 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/token/AuthToken.java
> +public class AuthToken {
별도의 클래스로 정의할 필요가 있을까엽

2022-06-23 15:14 UTC, enif-lee commented
@yeonnex 혹시 로컬 작업중인 부분이 푸시가 안된걸까요?

2022-06-30 12:40 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/UserService.java
> +public class UserService {
삭제 완료했습니다.
무지성 커밋의 흔적입니다...

2022-06-30 12:42 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserController.java
> +//    @PostMapping("/test") // POST 요청은 csrf 설정을 따로 해주지 않는다면 다른 서버에서 POST 등 리소스의 상태를 변경하는 동작 아예 수행 불가.
삭제 완료했습니다 ✅

2022-06-30 13:53 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/UserService.java
> +public class UserService {
삭제가 안되었는데, 로컬 커밋은 꼭 푸시 부탁드립니다~

2022-06-30 16:37 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/AuthController.java
> +        UserRefreshToken userRefreshToken = userRefreshTokenRepository.findByEmailAndRefreshToken(email, refreshToken);
네! 로그인 중복 체크를 위해 이메일 기반으로 찾는 것 말고는 기존에 이메일로 조회하는 방식들 진성님 말씀대로 pk(id) 기반으로 조회하는 것으로 바꿨습니다. jwt 토큰에도 pk 값인 "id" 를 넣었습니당!

제가 저번에 말씀드렸던 저희 회사 서비스의 경우 pk 가 이메일이었어여...ㅎ

조언 넘 감사함당 역시 역시~👍

2022-07-02 01:54 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/AuthController.java
> +
갓텔리제이의 `option + command + L` 단축키 적용을 생활화하도록 하겠슴다... 🫡

2022-07-02 01:55 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        // HttpHeader 와 HttpBody 를 하나의 오브젝트에 담기
ㅋㅋ 와타시 기억력 붕어 ㅋㅋ 🐟

2022-07-02 03:03 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        System.out.println("==response==" + response1);
삭제 완료 ✅

2022-07-02 03:03 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        ResponseEntity<String> response2 = rt2.exchange(
완료 ✅

2022-07-02 03:03 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserController.java
> +    @GetMapping("/") // 메인 페이지. 소셜 로그인할 수 있는 링크들 있음.
아무 용도도 아니었음을... 삭제 완료 ✅

2022-07-02 03:04 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserDetailController.java
> +public class UserDetailController {
ㅋㅋ 맞는 말씀... 삭제 완료 ✅

2022-07-02 03:04 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/user/UserDetailController.java
> +    @GetMapping("/email")
정답 💯

2022-07-02 03:05 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/auth/AuthReqModel.java
> +public class AuthReqModel {
삭제 완료 ✅🐟

2022-07-02 03:07 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/user/User.java
> +@Table(name = "USER")
네이밍 컨벤션 어떻게 할까요... 보통 소문자를 쓰는 편인가요...? 조언을 구합니다... 🧐

2022-07-02 03:42 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/OAuth2Service.java
> +                throw new OAuthProviderMissMatchException(
시나리오는 아래와 같습니다.

1. 최초 카카오로 로그인했을 때, 해당 이메일이 "abcd@gmail.com" 로 로그인된 사용자 있음.
2. 근데 이후 이 사용자가 카카오가 아닌 다른 벤더를 사용하여 로그인했을 때 해당 이메일이 만약 "abcd@gmail.com" 이라면 이 값은 이미 DB 에 존재하므로, 처음 로그인 한 카카오로 로그인해달라는 메시지를 주기 위해 만들었습니다.

이메일을 unique 한 값으로 주기 위한 의도입니다!

2022-07-02 03:45 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/OAuth2Service.java
> +@RequiredArgsConstructor
UUID 말씀하시는 건가용? 
소셜 로그인에서 회원가입시 password 를 임의로 지정해주기 위한 용도입니다 😗

2022-07-02 03:45 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/common/ApiResponse.java
> +public class ApiResponse<T> {
압도적 동의를 표합니다...🫡

2022-07-02 03:46 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/config/properties/AppProperties.java
> +public class AppProperties {
맞슴다 정답 💯

2022-07-02 03:50 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/config/security/SecurityConfig.java
> +                .antMatchers("/api/**/user/**").hasAnyAuthority(RoleType.USER.getCode()) // "/api/**" USER 권한이 있어야 접근가능.
아하... 무지성 블로그 코드 따라치기의 폐해가 여기에 또 있군여... 
진성님 의견대로 반영 완료했습니다 👍

2022-07-02 03:52 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/entity/RoleType.java
> +    GUEST("ROLE_GUEST", "게스트 권한");
게스트 권한을 혹시 어떤 용도로 사용하려 하시는 건지 알려주실 수 있으실까영?
약간 anonynous 비슷한 걸로 이해해도 될까요?! 🤔

2022-07-02 03:53 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/filter/TokenAuthenticationFilter.java
> +        log.info("이후 필터를 타는가?");
... 압도적 인정 ... 앞으로 주석이나 로그를 남길때에는 한번 더 생각하는 사람이 되겠읍니다...
![image](https://user-images.githubusercontent.com/82166132/176985583-db4151d3-4e88-4c52-9bac-c9e7d2775eff.png)

2022-07-02 04:22 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        if (response.isCommitted()){
무지성 블로그 코드 따라치기의 폐해입니다...
로직상 빠져도 되는 별 의미없는 코드입니다. 가차없이 삭제 완료했습니다 ✅

2022-07-02 06:50 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        response.setHeader("access_token" , accessToken.getToken());
아하...! 그렇군요!
body 에 담는 방식으로 변경 완료했습니다!

각 토큰의 만료시간의 경우 어차피 서버에서 검증할 것이기 떄문에 토큰 모델에 담지 않았습니다! 

결과적으로 아래와 같은 json 바디가 내려갑니다!
```
{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5ZW9ubmV4QGdtYWlsLmNvbSIsImlkIjoxLCJyb2xlIjoiVVNFUiIsImV4cCI6MTY1Njc0MjAxOH0.cEGx8K2gkpI0DWhvgvMl5bklq9bq1UPc2nXxkbNL33g",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5ZW9ubmV4QGdtYWlsLmNvbSIsImlkIjoxLCJyb2xlIjoiVVNFUiIsImV4cCI6MTY1NzM0NjgxOH0.x6sOYuIrLbKsx18fi0aBxE4WFjQix-CmWuwgklFoAZk"
}
```

2022-07-02 06:54 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +                    if(authorizedURI.getHost().equalsIgnoreCase(clientRedirectUri.getHost())
굳이 필요없는 로직이라 삭제했습니다 ✅

2022-07-02 06:54 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/info/OAuth2UserInfoFactory.java
> +//            case KAKAO: return new KakaoOAuth2UserInfo(attributes);
카카오 구현 완료했슴다 ✅

2022-07-02 06:55 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/info/impl/GoogleOAuth2UserInfo.java
> +public class GoogleOAuth2UserInfo extends OAuth2UserInfo {
아하 그렇군여...!

2022-07-02 06:57 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/CustomOAuth2UserService.java
> +    private OAuth2User process(OAuth2UserRequest userRequest,OAuth2User user){
아하 그렇군요 2
함수명 변경했고, 주석 지우는 것도 완료했슴다 ✅

2022-07-02 07:00 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/CustomOAuth2UserService.java
> +        if(userInfo.getUserName() != null && ! ( userInfo.getUserName().equals(userInfo.getImageUrl()) )){
이미지 url 비교하는 것으로 완료했습니다 ✅

2022-07-02 07:01 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +        // access token
삭제 삭제 완료 완료 ✅

2022-07-02 07:29 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +        AuthToken newAccessToken = tokenProvider.createAuthToken(
refresh token 의 경우, 최초 발급했던 리프레시 토큰(기한은 처음 발급일로부터 7일)을 다시 담아 보냅니다. 
새로 발급하지 않아요!

refresh token 기한까지 지나면, 사용자는 다시 로그인을 해야합니다 🥹

2022-07-02 07:30 UTC, enif-lee commented
@ohjinhokor 앗 ㅋㅋ 추가적으로 작업하실 부분은 항상 별도 브랜치로 만드신 후 작업해주세용

2022-07-02 07:31 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +        AuthToken newAccessToken = tokenProvider.createAuthToken(
오호 리프레시 토큰도 새로 담아서 보내는게 좋지 않을까엽

2022-07-02 07:32 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +                    if(authorizedURI.getHost().equalsIgnoreCase(clientRedirectUri.getHost())
굿

2022-07-02 07:36 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/filter/TokenAuthenticationFilter.java
> +        log.info("이후 필터를 타는가?");
ㅋㅋㅋㅋㅋㅋ

2022-07-02 07:48 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/entity/RoleType.java
> +    GUEST("ROLE_GUEST", "게스트 권한");
넹 가입전에도 여전히 타이머는 사용할 수 있어야할 것 같아서요!

이렇게되면 익명의 유저가 가입 유저로 변경할 수 있도록 해야할 듯?!

2022-07-02 07:48 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/config/security/SecurityConfig.java
> +                .antMatchers("/api/**/user/**").hasAnyAuthority(RoleType.USER.getCode()) // "/api/**" USER 권한이 있어야 접근가능.
굿

2022-07-02 07:49 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/config/properties/AppProperties.java
> +public class AppProperties {
굿

2022-07-02 07:49 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/common/ApiResponse.java
> +public class ApiResponse<T> {
굿

2022-07-02 07:55 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/service/OAuth2Service.java
> +@RequiredArgsConstructor
이거는 왜 이렇게 리뷰 달았는지, 기억이 안나네요 무시하셔도 댑니당 ㅋㅋ

2022-07-02 07:55 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/AuthController.java
> +
굿..

2022-07-02 07:57 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/AuthController.java
> +        UserRefreshToken userRefreshToken = userRefreshTokenRepository.findByEmailAndRefreshToken(email, refreshToken);
아하 굿굿 좋습니다~

2022-07-02 07:58 UTC, enif-lee commented on server/.idea/workspace.xml
> +    <option name="SHOW_DIALOG" value="false" />
`.idea` 폴더는 삭제하시고 gitignore 부탁드릴게용

2022-07-02 08:03 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/auth/OAuthController.java
> +        params.add("client_secret", "aTnSYwnw2qCJ0zZ9Br74HUUoWS0kMVwy");
별도 application.yml로 변경

2022-07-02 08:04 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/user/User.java
> +@Table(name = "USER")
lower_snakecase로 결정 땅땅

2022-07-02 08:06 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/info/impl/GoogleOAuth2UserInfo.java
> +public class GoogleOAuth2UserInfo extends OAuth2UserInfo {
State ㄲ?

2022-07-02 08:06 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        response.setHeader("access_token" , accessToken.getToken());
굿굿

2022-07-02 08:14 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +    public void refreshToken(HttpServletRequest request, HttpServletResponse response){
아하... 그렇군요...

클라이언트에서 서버로 요청시 access token 만 보내면 되게  수정했습니다!

access token 만료시, 
`GET /refresh` 로 요청하시면 access token 을 새로 발급받을 수 있으십니다 😊

2022-07-02 08:19 UTC, yeonnex commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/token/AuthToken.java
> +public class AuthToken {
이것 또한.. 무지성 따라치기의 폐해...
현재 이 클래스를 프로젝트의 여러곳에서 쓰고 있어서 고치려면 시간이 좀 걸릴듯합니다...

필수 기능들 구현 후에 다시 고쳐보겠습니다...! 흑흑...

2022-07-02 08:21 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/oauth/service/IssueRefreshService.java
> +    public void refreshToken(HttpServletRequest request, HttpServletResponse response){
굿

2022-07-03 09:52 UTC, enif-lee approved these changes
@yeonnex 우선 요 PR은 머지하고 나머지 자잘한 개선 기능들은 PR로 분리해서 올려주세용~

2022-07-04 03:34 UTC, merged