Feat/timer
gdsc-ssu/emotimer pull request #4
Opened 2022-06-18 05:38 UTC by ohjinhokor

2022-06-18 08:13 UTC, enif-lee requested changes

2022-06-18 08:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerController.java
> +	public ResponseEntity<CreateTimerResponse> createTimer(MakeTimerRequest req) {
create timer가 있을 이유가 있나여?

2022-06-18 08:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerController.java
> +	public ResponseEntity<CreateTimerResponse> createTimer(MakeTimerRequest req) {
operate를 할 때 없다면 생성하는 형태로 로직이 구성되었으면 좋겠습니다.

2022-06-18 08:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/request/OperateTimerRequest.java
> +    private long serverTime;
serverTime을 보내는 이유가 있을 것 같은데 어떤 이유일까요?( 뭔가 기억이 안남

2022-06-18 08:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/response/GetTimerResponse.java
> +    private TimerHub timerHub;
timer hub 는 반환하는 이유가 무엇인가요?

2022-06-18 08:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerHub.java
> +    private Emoji emoji;
Category 로 rename해주세요~~

2022-06-18 08:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerHub.java
> +    private Long totalSeconds;
seconds보단 mili니까 차라리 time이 나은 것 같아요

2022-06-18 08:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerHub.java
> +public class TimerHub {
TimerHub보단 다른 이름이 좋을 것 같은데.Timer이 낫지 않을까요?

2022-06-18 11:39 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerController.java
> +	public ResponseEntity<CreateTimerResponse> createTimer(MakeTimerRequest req) {
setTimerSettings 메서드로 메서드명 변경

2022-06-18 12:06 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/response/GetTimerResponse.java
> +    private TimerHub timerHub;
timerhub가 timer입니다. 변수명 변경할게요!

2022-06-18 12:06 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerHub.java
> +public class TimerHub {
동의합니다

2022-06-18 12:06 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerHub.java
> +    private Long totalSeconds;
변수명 totalTime으로 변경

2022-06-18 12:06 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerHub.java
> +    private Emoji emoji;
나중에 서연님이 Category라는 Enum을 만드시면 그걸로 변경하겠습니다.

2022-06-23 14:24 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerController.java
> +	public ResponseEntity<CreateTimerResponse> createTimer(MakeTimerRequest req) {
굿

2022-06-23 15:13 UTC, enif-lee approved these changes
고생하셨습니다. 코멘트 확인해주시고 머지하셔도 좋습니닷

2022-06-23 15:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerController.java
> +		return ResponseEntity.ok("ok");
반환값이 없을 경우에는 noContent로 내려주셔도 괜찮습니다.

2022-06-23 15:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/request/OperateTimerRequest.java
> +public class OperateTimerRequest {
이 파일은 삭제해도 괜찮지 않을까요 ?

2022-06-23 15:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerHistoryController.java
> +	private final TimerHistoryService timerHistoryService;
`// TODO implement this` 한번 남겨주세요

2022-06-23 15:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/request/ResetTimerRequest.java
> +	private long userId;
미리 제거해놔도 괜찮을 것 같긴합니당

2022-06-23 15:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/response/OperateTimerResponse.java
> +public class OperateTimerResponse {
삭제

2022-06-23 15:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/response/SetTimerSettingsResponse.java
> +	private Timer timer;
엔티티는 왠만하면 바로 응답 개체에 사용하지 말고 ReadModel(Dto같은 것) 클래스를 재정의해서 내려주는게 나을 것 같아요.

아니면 Response클래스에 중복 정의해도 괜찮습니다.

2022-06-23 15:13 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/Timer.java
> +	private long timerId;
Id 체계는 가급적이면 sequence number 보단 string으로 사용하는게 좋아보입니다. README작성할 때 컨벤션을 맞췄던 것 같은데용

2022-06-23 15:54 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerController.java
> +		return ResponseEntity.ok("ok");
넵 알겠습니다.

2022-06-23 15:55 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/request/OperateTimerRequest.java
> +public class OperateTimerRequest {
넵 알겠습니다.

2022-06-23 15:56 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/controller/timer/TimerHistoryController.java
> +	private final TimerHistoryService timerHistoryService;
넵 알겠습니다.

2022-06-23 15:56 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/request/ResetTimerRequest.java
> +	private long userId;
요거는 나중으로..ㅋㅋㅋㅋㅋㅋㅋ

2022-06-23 15:57 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/response/OperateTimerResponse.java
> +public class OperateTimerResponse {
삭제완료

2022-06-23 16:08 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/Timer.java
> +	private long timerId;
UUID로 적용했습니다.

2022-06-23 16:18 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/dtos/timer/response/SetTimerSettingsResponse.java
> +	private Timer timer;
Response 클래스 수정했습니다

2022-06-24 03:50 UTC, enif-lee commented
@yeonnex 도 서로 리뷰 해도 좋을 것 같아요

2022-06-25 14:55 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerStatus.java
> +}
이 enum 클래스는 Timer Entity와 관계가 깊은데 그것을 코드로 표현하기 위해 Timer Entity와 같은 파일에 이 Enum을 함께 정의하는 것이 좋을까요?? 고민입니당..

2022-06-26 13:47 UTC, enif-lee commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerStatus.java
> +}
아하이거 말씀하시는 것이였군여. 이런 Status는 별도로 정의해도 되고 entity내에 nested로 정의해도 괜찮을 것 같아요.

```java
class Timer {
    enum Stats {
        // do something
    }

}
```

2022-06-26 14:22 UTC, ohjinhokor commented on server/timer-service/src/main/java/com/gdsc/timerservice/api/entity/timer/TimerStatus.java
> +}
넵 감사합니다! 우선 별도로 정의해서 사용하겠습니다!

2022-06-26 14:25 UTC, merged